### PR TITLE
remove guides and fix copy button

### PR DESCRIPTION
**Pull request by Sophie-edgeworx**
## Summary

Brief explanation of the proposed changes.

Link to Shortcut story.

## Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

## Checks

- [x] Run `npm run test` locally.
- [x] Create a Pull Request (follow the [GitHub flow](https://guides.github.com/introduction/flow/)) and [Conventional Commits Specification](https://www.conventionalcommits.org/en/v1.0.0/))
- [x] Verify any structural/CSS changes on all screen sizes (if relevant)

### CODE REVIEW

**Comment by ag-edge** [comment]
content/en/docs/guides/deploy.md line 274
docs\README.md line 343

Maybe docs\config\_default\menus\menus.en.toml see calls to AI page

docs\content\en\docs\more\changelog.md line 60

**Comment by Sophie-edgeworx** [comment]
I fixed/removed broken links, there is just 1 remains that supposed to point to a future correct address.

**Comment by ag-edge** [comment]
I see it is the API URL. You prob know better than me, but is that the correct URL once we move domains?

**Comment by Sophie-edgeworx** [comment]
> I see it is the API URL. You prob know better than me, but is that the correct URL once we move domains?

Alex, I hoped you would be the one who knows. Maybe Brian or Raja?

**Comment by ag-edge** [comment]
Oh yea, Raja or Neil! Sorry!

**Pull request merged**
